/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "doc",
      id: "intro",
    },
    {
      type: "category",
      label: "Observability",
      link: {
        type: "generated-index",
        description: "Here's a list of a popular Observability Tools",
      },
      items: [
        {
          type: "category",
          label: "Beginners",
          link: {
            type: "generated-index",
            description:
              "Beginners guide to start off with devops,Topics here are of basic introduction and goes indepth furthur",
          },
          items: [
            {
              type: "doc",
              id: "observability/beginners/datadog",
            },
            {
              type: "doc",
              id: "observability/beginners/grafana",
            },
            {
              type: "doc",
              id: "observability/beginners/middleware",
            },
            {
              type: "doc",
              id: "observability/beginners/prometheus",
            },
            {
              type: "doc",
              id: "observability/beginners/signoz",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Provisioning",
      link: {
        type: "generated-index",
        description: "Here's a list of a popular Provisioning Tools",
      },
      items: [
        {
          type: "category",
          label: "Beginners",
          link: {
            type: "generated-index",
            description:
              "Beginners guide to start off with devops,Topics here are of basic introduction and goes indepth furthur",
          },
          items: [
            {
              type: "doc",
              id: "provisioning/beginners/ansible",
            },
            {
              type: "doc",
              id: "provisioning/beginners/chef",
            },
            {
              type: "doc",
              id: "provisioning/beginners/puppet",
            },
            {
              type: "doc",
              id: "provisioning/beginners/terraform",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Orchestration",
      link: {
        type: "generated-index",
        description: "Here's a list of a popular Orchestration Tools",
      },
      items: [
        {
          type: "category",
          label: "Beginners",
          link: {
            type: "generated-index",
            description:
              "Beginners guide to start off with devops,Topics here are of basic introduction and goes indepth furthur",
          },
          items: [
            {
              type: "doc",
              id: "orchestration/beginners/dockerswarm",
            },
            {
              type: "doc",
              id: "orchestration/beginners/ecs",
            },
            {
              type: "doc",
              id: "orchestration/beginners/gke",
            },
            {
              type: "doc",
              id: "orchestration/beginners/kubernetes",
            },
            {
              type: "doc",
              id: "orchestration/beginners/openshift",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Provisioning",
      link: {
        type: "generated-index",
        description: "Here's a list of a popular Provisioning Tools",
      },
      items: [
        {
          type: "category",
          label: "Beginners",
          link: {
            type: "generated-index",
            description:
              "Beginners guide to start off with devops,Topics here are of basic introduction and goes indepth furthur",
          },
          items: [
            {
              type: "category",
              label: "argocd",
              items: [
                {
                  type: "doc",
                  id: "cicd/beginners/argocd/intro",
                },
                {
                  type: "doc",
                  id: "cicd/beginners/argocd/dockerdesktop",
                },
              ],
            },
            {
              type: "doc",
              id: "cicd/beginners/dagger",
            },
            {
              type: "doc",
              id: "cicd/beginners/drone",
            },
            {
              type: "doc",
              id: "cicd/beginners/jenkins",
            },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
